# This docker compose file is for use during development only
version: '3'
services:
  # PostgreSQL
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: foostrack
      POSTGRES_USER: foostrack

  # A simple database access utility for development
  adminer:
    image: adminer:4
    ports:
      - '9000:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
